# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"

base: &base
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_unicode_ci

default: &default
  <<: *base
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>

default_replica: &default_replica
  <<: *base
  pool: 5
  username: <%= ENV['DB_REPLICA_USER'] || ENV['DB_USER'] %>
  password: <%= ENV['DB_REPLICA_PASSWORD'] || ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_REPLICA_HOST'] || ENV['DB_HOST'] %>
  port: <%= ENV['DB_REPLICA_POST'] || ENV['DB_PORT'] %>

development:
  primary:
    <<: *default
    username: <%= ENV.fetch("DB_USER", root) %>
    database: bikehikaku_development
  replica:
    <<: *default_replica
    username: <%= ENV.fetch("DB_USER", root) %>
    database: bikehikaku_development
    replica: true

test:
  primary:
    <<: *default
    username: root
    database: bikehikaku_test
  replica:
    <<: *default_replica
    username: root
    database: bikehikaku_test
    replica: true

production:
  primary:
    <<: *default
    database: <%= ENV['DB_DATABASE'] %>
  replica:
    <<: *default_replica
    database: <%= ENV['DB_DATABASE'] %>
    replica: true
